Fix a small bug which never should happen
SuperMeepBoy/wikitransbot pull request #29
Opened 2022-05-04 20:26 UTC by ajabep

2022-05-04 20:35 UTC, SuperMeepBoy requested changes
I did that before but I'm pretty sure the request automatically parse the space and accents correctly. I did not imagine it could be the origin of a bug.

What is the bug you intend to fix ? Can you change the commit name accordingly so we get a better understanding of what is fixed ? :)

Thanks a lot for your contribution !

2022-05-04 21:14 UTC, ajabep commented
Fix an HTTP Parameter Pollution bug (not a vuln here)

Before this commit, if a user put a char `&` in keywords (which should never happen), due to the concatenation without encoding the value, the server will handle only what comes before this char as the parameter value. What comes after will be considered as another HTTP parameter.

Example:  
If a user is searching `test & foobar`, the URL will be as `term=test & foobar`.
Thus, the value of `term` parameter will be `test ` and the following parameter is ` foobar`.
If we URL-encode the searched terms, the URL will be `term=test%20%26%20foobar`.
Thus, the value of `term` parameter will be `test & foobar`, as terms searched by the user.

Usually an HPP is a vulnerability, however, here it's not a vulnerability, only a bug.

2022-05-07 13:29 UTC, SuperMeepBoy approved these changes

2022-05-07 13:49 UTC, SuperMeepBoy commented
LGTM ! Merci ! :)

2022-05-07 13:50 UTC, merged